# I install the modules separately instead of looping because it allows me to
# uninstall/absent the package. naturally it's unlikely with these specific
# modules, but overall experience has told me that I'd rather be explicit

- name: update apt cache
  apt:
    update_cache: yes

- name: install manpages
  apt:
    name: "{{ packages }}"
    force_apt_get: true
    state: present
  vars:
    packages:
    - manpages
    - manpages-posix
    - manpages-posix-dev

- name: install command line tools for errno
  apt:
    name: "{{ packages }}"
    force_apt_get: true
    state: present
  vars:
    packages:
    - moreutils
