- hosts: localhost
  gather_facts: yes

  roles:
    - { role: ssh, become: yes }
    - dotfiles
    - { role: apt_development_tools, become: yes }
    - { role: apt_window_manager, become: yes }
    - { role: apt_system_programming, become: yes }
