# I install the modules separately instead of looping because it allows me to
# uninstall/absent the package. naturally it's unlikely with these specific
# modules, but overall experience has told me that I'd rather be explicit

- name: update apt cache
  apt:
    update_cache: yes

- name: install sysstat
  apt:
    name: sysstat
    state: present

- name: install numactl
  apt:
    name: numactl
    state: present

- name: install procps
  apt:
    name: procps
    state: present

- name: install net-tools
  apt:
    name: net-tools
    state: present

- name: install iptraf
  apt:
    name: iptraf
    state: present

- name: install wireshark
  apt:
    name: wireshark
    state: present

- name: install htop
  apt:
    name: htop 
    state: present
