# useful dxocs in the event zlib issues are encounterd in the future
# https://www.1stbyte.com/2005/06/26/configure-and-compile-python-with-zlib/

- name: downloading python3.6 source from official python site
  get_url: 
    url: https://www.python.org/ftp/python/3.6.3/Python-3.6.3.tar.xz
    dest: ~/
  register: python36

- name: declaring src directory fact for cleanup actions
  set_fact:
    python36_src_dir: "{{ python36.dest }}"

- name: creating dir to unpack src into and build out of
  file:
    path: ~/python36
    state: directory
  register: python36_build

- name: declaring build dir fact for cleanup actions
  set_fact:
    python36_build_dir: "{{ python36_build.path }}"
    
- name: unarchiving python3.6 source code to enable make targeting
  unarchive:
    src: "{{ python36_src_dir }}"
    dest: "{{ python36_build_dir }}"
  register: python36_unzip

- name: getting a list of items inside the newly created python36 directory
  find:
    paths: "{{ python36_build_dir }}"
    file_type: any
  register: file_find

- name: declaring unarchived python36 src location for make targeting
  set_fact:
    build_target: "{{ file_find.files[0].path }}"

- name: installing zlib requirements packages to compile with zlib support
  apt: 
    name: "{{ item }}"
  with_items:
    - zlib1g-dev
    - libssl-dev
    - libffi-dev
    - python3-dev
  become: true

- name: configuring build target from python36 src
  command: ./configure --with-zlib=/usr/include --enable-optimizations
  args:
    chdir: "{{ build_target }}"

- name: building default python36 target for downstream install
  make:
    chdir: "{{ build_target }}"

- name: make-installing python36 src into binary
  command: make install
  args: 
    chdir: "{{ build_target }}"
    creates: /usr/local/bin/python3.6
  become: true
  become_user: root
  become_method: sudo

- name: removing build directory
  file:
    path: "{{ python36_build_dir }}"
    state: absent
  become: true

- name: removing archive directory
  file:
    path: "{{ python36_src_dir }}"
    state: absent
  become: true
