- name: update apt cache
  apt:
    update_cache: yes

- name: installing development tooling
  apt:
    name: "{{ packages }}"
    force_apt_get: true
    state: present
  vars:
    packages:
    - vim        # install normal vim8, ubu18.04 repos now carry, no need for neovim
    - ctags      # automatically create tags files for easy code searching
    - screen     # decent terminal multiplexing, will need to set this to default plexer

- name: install/update vim plugins
  command: vim +PlugUpdate +qall
